### PR TITLE
Fix tests not building on Linux

### PR DESCRIPTION
**Pull request by TheNeikos**
This PR fixes tests from building + some warnings

It also adds linux to CI, making sure such errors don't get merged

### CODE REVIEW

**Comment by TheNeikos** [comment]
Huh, so it fails because it can't find the `dll` :D

Which makes sense, cause they'd be .so on linux. Lemme check how to fix that

**Comment by TheNeikos** [comment]
Alright, had to figure out that the tests were skipped (without being marked as such) when you don't have python installed :D 

It is now working for me, with python installed.

**Comment by ralfbiedert** [comment]
FYI, I'm going to merge this regardless just so you have "Contributor" permissions, since otherwise I have to constantly manually approve your runs.

**Comment by ralfbiedert** [comment]
(If you can please also fix the Windows build issue, otherwise I'll look into that later)

**Comment by ralfbiedert** [comment]
Thanks for the PR btw :)

**Comment by TheNeikos** [comment]
> FYI, I'm going to merge this regardless just so you have "Contributor" permissions, since otherwise I have to constantly manually approve your runs.

Yeah, shame GitHub is not super ergonomic here... and I don't have a windows machine to test.

Sorry for the noise!

> (If you can please also fix the Windows build issue, otherwise I'll look into that later)

I've opened #132 for that

**Pull request merged**
