### PR TITLE
Formatting improvements for C backend

### PR DESCRIPTION
**Pull request by pixsperdavid**
- Inline documentation now added for functions
- Spacing added between each function definiton
- Bracing for enums/structs now customisable from config

### CODE REVIEW

**Comment by ralfbiedert** [comment]
Thanks! 

Could you make the additional spacing in the header file optional, as well as writing comments?

I don't know how the style is called, but at my company headers look like so:

```
typedef struct my_library_phantomu8
    {
    uint32_t x;
    } my_library_phantomu8;

uint8_t primitive_u8(uint8_t x);
uint16_t primitive_u16(uint16_t x);

// ## primitive_u8(x)
// 
// Documentation for primitive_u8 ...
//
// ### Signature
//
// uint8_t primitive_u8(uint8_t x);`
//
// ---
// 
// ## primitive_u16(x)
// ...
```

In other words a compact list of types and functions, and only then a list of all documentation, concatenated and / or available as Markdown. 

The in-header documentation generation isn't done yet, but I'd like to be able to preserve the current style behind some config options.

**Comment by pixsperdavid** [comment]
Have added a `CDocumentationStyle` setting to the config to customize behaviour. Currently options are 'None' (matches previous) and 'Inline', however your non-inline style can be added as an option to this when the feature is ready.

I have to say that I've personally never seen documentation in a C header file laid out as in your example. The closest thing to a standard in C documentation is doxygen, (incidentally, translating from rustdoc format to this could be a useful future feature), however by not including the doc in inline comments next to each declaration I believe you would lose the ability for IDEs to automatically parse it?

The additional line spacing now will only apply in inline documentation mode. I wonder if there's a better way to express this with the IndentWriter? I believe that the logic should essentially be - single line declarations (with no inline doc) can be preceded/followed without a line space, multi-line declarations (or any with inline doc) should be seperated from other declarations by a line space.

**Comment by ralfbiedert** [comment]
> I have to say that I've personally never seen documentation in a C header file laid out as in your example. The closest thing to a standard in C documentation is doxygen, (incidentally, translating from rustdoc format to this could be a useful future feature), however by not including the doc in inline comments next to each declaration I believe you would lose the ability for IDEs to automatically parse it?

TBH I'm not actively involved or close to our in-house hardcore C people. IIRC it primarily comes from the mindset of "read the headers if you want a quick API overview, read the proper documentation if you want to understand the details".  Losing the ability to get inline IDE documentation is probably true. Just to be clear, I'm not overly defending the style, I just want Interoptopus to be able to produce it. 

> (incidentally, translating from rustdoc format to this could be a useful future feature),

I also thought about that briefly for C# and Python, but ended up with a few unsolved problems. For example, how to populate `<argument name="x"></argument>` (or so) fields some languages want but Rust doesn't have?

For some of our public APIs we ultimately said having an online page embedded in the rest of our site gives most bang for the buck, so we extract Markdown documentation, prefix it with some custom styling and run embed it in our Hugo project ([sample](https://vr.tobii.com/sdk/develop/ocumen/ocumen-io-python-api/))


> I wonder if there's a better way to express this with the IndentWriter?

I'd have to have a look at that myself, haven't touched that code in a while. I think `IndentWriter` really only exists to configure "4 spaces" or "1 tab" (and frankly I considered removing it and just yolo 4 spaces). Handling newlines were so far meant to be handled in some "outer loop", like `write_function_definition`, but I dimly remember not having found the perfect spot for more complex new-line logic, e.g.,  when transitioning between types and functions (some of which might be empty).

**Comment by pixsperdavid** [comment]
> TBH I'm not actively involved or close to our in-house hardcore C people. IIRC it primarily comes from the mindset of "read the headers if you want a quick API overview, read the proper documentation if you want to understand the details". Losing the ability to get inline IDE documentation is probably true. Just to be clear, I'm not overly defending the style, I just want Interoptopus to be able to produce it.

Fair enough! This further suggests that the possibility that by parsing the rust doc, the generated doc could be split into multiple sections. For example, add the brief description and the argument descriptions inline with the function, and put the entire doc comment at a point later in the file.

> I also thought about that briefly for C# and Python, but ended up with a few unsolved problems. For example, how to populate `<argument name="x"></argument>` (or so) fields some languages want but Rust doesn't have?

Could this not be parsed from the 'Arguments' section of a rust doc comment (if present)? E.g. (from https://doc.rust-lang.org/rust-by-example/meta/doc.html)

```rust
/// Returns a person with the name given them
///
/// # Arguments
///
/// * `name` - A string slice that holds the name of the person
```

could parse to C# XMLDoc:

```csharp
/// <summary>
/// Returns a person with the name given them
/// </summary>
/// <param name="name"> A string slice that holds the name of the person.</param>
```

or in C Doxygen:

```c
/// @brief Returns a person with the name given them
/// @param name A string slice that holds the name of the person.
```


> I'd have to have a look at that myself, haven't touched that code in a while. I think `IndentWriter` really only exists to configure "4 spaces" or "1 tab" (and frankly I considered removing it and just yolo 4 spaces). Handling newlines were so far meant to be handled in some "outer loop", like `write_function_definition`, but I dimly remember not having found the perfect spot for more complex new-line logic, e.g., when transitioning between types and functions (some of which might be empty).

I spent a while trying to create a `DeclarationWriter` wrapper around the `IndentWriter`, the idea being that when dropped it would determine how many lines long a declaration was and insert blank lines before/after to pad it if multiline. I tried a few approaches but the key issue is that it's not currently possibly to know whether the last character added to the file was a line break or not, hence unnecessary line breaks would get added with every multi-line declaration.

**Comment by ralfbiedert** [comment]
> Could this not be parsed from the 'Arguments' section of a rust doc comment (if present)? 

Maybe, but I probably wouldn't want to write that sort of code myself :)  Not opposed to you / someone trying, but this should be an experiment first to see how brittle that logic turns out to be, how well it practically works with various backend requirements (e.g., Doxygen / whatever-C#-is-using / JavaDoc, ...).

**Pull request merged**
